const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying TribeConnect with account:", deployer.address);
  console.log("Account balance:", ethers.utils.formatEther(await deployer.getBalance()), "ETH");

  // Deploy
  const TribeConnect = await ethers.getContractFactory("TribeConnect");
  const contract = await TribeConnect.deploy();
  await contract.deployed();

  console.log("\n✅ TribeConnect deployed to:", contract.address);
  console.log("   Transaction hash:", contract.deployTransaction.hash);
  console.log("   Block number:", contract.deployTransaction.blockNumber);

  // Write address to lib/constants for the frontend to pick up
  const constantsPath = path.join(__dirname, "../../lib/constants.js");
  const networkName = hre.network.name;

  let existing = {};
  if (fs.existsSync(constantsPath)) {
    const content = fs.readFileSync(constantsPath, "utf-8");
    // Parse existing constants
    const match = content.match(/export const CONTRACT_ADDRESSES = ({[\s\S]*?});/);
    if (match) {
      try { existing = eval("(" + match[1] + ")"); } catch(_) {}
    }
  }

  existing[networkName] = contract.address;

  const content = `// Auto-generated by deploy.js — do not edit manually
// Last deployed: ${new Date().toISOString()}

export const CONTRACT_ADDRESSES = ${JSON.stringify(existing, null, 2)};

export const SUPPORTED_CHAINS = {
  polygon:   137,
  amoy:      80002,
  localhost: 1337,
};

export const IPFS_GATEWAY = process.env.NEXT_PUBLIC_IPFS_GATEWAY || "https://gateway.pinata.cloud/ipfs/";
`;

  fs.mkdirSync(path.dirname(constantsPath), { recursive: true });
  fs.writeFileSync(constantsPath, content);
  console.log("\n📝 Contract address written to lib/constants.js");

  // Verify on Polygonscan (if not localhost)
  if (networkName !== "hardhat" && networkName !== "localhost") {
    console.log("\n⏳ Waiting 6 confirmations before verifying...");
    await contract.deployTransaction.wait(6);
    try {
      await hre.run("verify:verify", {
        address: contract.address,
        constructorArguments: [],
      });
      console.log("✅ Contract verified on Polygonscan");
    } catch (e) {
      console.log("⚠️  Verification failed:", e.message);
    }
  }

  console.log("\n🚀 Deployment complete!");
  console.log("   Network:  ", networkName);
  console.log("   Address:  ", contract.address);
  console.log("   Explorer: ", networkName === "polygon"
    ? `https://polygonscan.com/address/${contract.address}`
    : networkName === "amoy"
    ? `https://amoy.polygonscan.com/address/${contract.address}`
    : "local"
  );
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
